push

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -95,24 +95,29 @@ jobs:
             sudo apt-get install -f -y
             sudo dpkg -i /opt/chromium-gost/plugin/cades-linux-ia32/*.deb || true
             sudo apt-get install -f -y
-            
-
-      - name: Run Selenium tests
+          
+          
+          # Запуск Selenium тестов с установленным расширением и проверкой сертификатов
+      - name: Run Selenium tests with Chromium-Gost Extension
         run: |
             chromium-gost --ignore-certificate-errors --user-data-dir=/tmp/temp_chrome_profile &
             sleep 5
             python3 test/autorization.py
         env:
-          DISPLAY: :99
+            DISPLAY: :99
 
-            # Новый шаг для вывода параметров запуска и проверки сертификатов
-
+          # Новый шаг для вывода параметров запуска и проверки сертификатов
       - name: Check Chromium-Gost parameters and certificates
         run: |
-                echo "Chromium-Gost parameters:"
-                ps aux | grep chromium-browser | grep -v grep || true  # Вывод параметров запуска, игнорируя сам grep процесса
+            echo "Chromium-Gost parameters:"
+            ps aux | grep chromium-browser | grep -v grep || true  # Вывод параметров запуска, игнорируя сам grep процесса
+          
+            echo "Installed certificates:"
+            ls /usr/local/share/ca-certificates/  # Проверка установленных сертификатов
+          
+            # Проверка наличия установленного расширения Chromium-Gost
+            echo "Installed Chromium-Gost extension:"
+            ls $HOME/.config/chromium/Default/Extensions/1.2.13_0.crx || echo "Chromium-Gost extension not found"
 
-                echo "Installed certificates:"
-                ls /usr/local/share/ca-certificates/
         env:
           DISPLAY: :99
